version: '3.9'
services:
  postgres:
    image: quay.io/debezium/example-postgres:nightly
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  debezium-server:
    image: debezium-server:local
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: debezium-server
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
      # JAVA_TOOL_OPTIONS: -javaagent:/debezium/lib/opentelemetry-javaagent.jar
      JAVA_OPTS: -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG
      OTEL_ENABLED: "true"
      ENABLE_OTEL: "true"
      # OTEL_JAVAAGENT_ENABLED: "true"
      # CLASSPATH: /debezium/lib/opentelemetry-api-1.30.1.jar:/debezium/lib/opentelemetry-context-1.30.1.jar:/debezium/lib/opentelemetry-extension-trace-propagators-1.30.1.jar:/debezium/lib/opentelemetry-instrumentation-api-1.30.1.jar:/debezium/lib/opentelemetry-instrumentation-api-semconv-1.30.1-alpha.jar:/debezium/lib/opentelemetry-javaagent.jar:/debezium/lib/opentelemetry-sdk-1.30.1.jar:/debezium/lib/opentelemetry-sdk-trace-1.30.1.jar:/debezium/lib/opentelemetry-semconv-1.30.1-alpha.jar:/debezium/lib/quarkus-opentelemetry-3.4.1.jar:/debezium/lib/opencensus-impl-core-0.31.1.jar:/debezium/lib/*.jar
    ports:
      - "8080:8080"
    volumes:
      - /Users/chris/.config/gcloud/application_default_credentials.json:/tmp/credentials/service-account.json
      - ./conf:/debezium/conf
